/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/utils/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/backup` | `/backup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/insights` | `/insights`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/learning` | `/learning`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/planner` | `/planner`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/thinking` | `/thinking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/timeline` | `/timeline`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/utils/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/backup` | `/backup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/insights` | `/insights`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/learning` | `/learning`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/planner` | `/planner`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/thinking` | `/thinking`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/timeline` | `/timeline`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../src/utils/notifications${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/backup${`?${string}` | `#${string}` | ''}` | `/backup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/insights${`?${string}` | `#${string}` | ''}` | `/insights${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/learning${`?${string}` | `#${string}` | ''}` | `/learning${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/planner${`?${string}` | `#${string}` | ''}` | `/planner${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/thinking${`?${string}` | `#${string}` | ''}` | `/thinking${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/timeline${`?${string}` | `#${string}` | ''}` | `/timeline${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/utils/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/backup` | `/backup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/insights` | `/insights`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/learning` | `/learning`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/planner` | `/planner`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/thinking` | `/thinking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/timeline` | `/timeline`; params?: Router.UnknownInputParams; };
    }
  }
}
